dmVyc2lvbjogMgp1cGRhdGVzOgogIC0gcGFja2FnZS1lY29zeXN0ZW06ICJu
cG0iCiAgICBkaXJlY3Rvcnk6ICIvIgogICAgc2NoZWR1bGU6CiAgICAgIGlu
dGVydmFsOiAiZGFpbHkiCgogIC0gcGFja2FnZS1lY29zeXN0ZW06ICJkZXZj
b250YWluZXJzIgogICAgZGlyZWN0b3J5OiAiLyIKICAgIHNjaGVkdWxlOgog
ICAgICBpbnRlcnZhbDogIndlZWtseSIK
